import { EnvVariables, MFEEnvVariables } from './vite-env'

const env: EnvVariables & MFEEnvVariables = {
  ENV_BUILD_VERSION: window.ENV?.ENV_BUILD_VERSION ?? import.meta.env.VITE_BUILD_VERSION,

  ENV_PUBLIC_PORTAL_URL:
    window.ENV?.ENV_PUBLIC_PORTAL_URL ?? import.meta.env.VITE_PUBLIC_PORTAL_URL,
  ENV_LEGACY_PORTAL_CART_URL:
    window.ENV?.ENV_LEGACY_PORTAL_CART_URL ?? import.meta.env.VITE_LEGACY_PORTAL_CART_URL,
  ENV_CONTRACT_CUSTOMERS_URL:
    window.ENV?.ENV_CONTRACT_CUSTOMERS_URL ?? import.meta.env.VITE_CONTRACT_CUSTOMERS_URL,

  ENV_SERVICE_PROVIDER_DOMAIN:
    window.ENV?.ENV_SERVICE_PROVIDER_DOMAIN ??
    import.meta.env.VITE_SERVICE_PROVIDER_DOMAIN,
  ENV_SERVICE_PROVIDER_MFE_BASENAME:
    window.ENV?.ENV_SERVICE_PROVIDER_MFE_BASENAME ??
    import.meta.env.VITE_SERVICE_PROVIDER_MFE_BASENAME,
  ENV_SERVICE_PROVIDER_SERVICE_PATH:
    window.ENV?.ENV_SERVICE_PROVIDER_SERVICE_PATH ??
    import.meta.env.VITE_SERVICE_PROVIDER_SERVICE_PATH,
  ENV_SERVICE_PROVIDER_OWNED_PROPERTIES_PATH:
    window.ENV?.ENV_SERVICE_PROVIDER_OWNED_PROPERTIES_PATH ??
    import.meta.env.VITE_SERVICE_PROVIDER_OWNED_PROPERTIES_PATH,

  ENV_FRONTEND_DEFAULT_LANG:
    window.ENV?.ENV_FRONTEND_DEFAULT_LANG ?? import.meta.env.VITE_FRONTEND_DEFAULT_LANG,

  ENV_AUTH_TOKEN_COOKIE_HOST:
    window.ENV?.ENV_AUTH_TOKEN_COOKIE_HOST ?? import.meta.env.VITE_AUTH_TOKEN_COOKIE_HOST,
  ENV_AUTH_TOKEN_COOKIE_NAME:
    window.ENV?.ENV_AUTH_TOKEN_COOKIE_NAME ?? import.meta.env.VITE_AUTH_TOKEN_COOKIE_NAME,
  ENV_REFRESH_TOKEN_COOKIE_NAME:
    window.ENV?.ENV_REFRESH_TOKEN_COOKIE_NAME ??
    import.meta.env.VITE_REFRESH_TOKEN_COOKIE_NAME,
  ENV_LANGUAGE_COOKIE_NAME:
    window.ENV?.ENV_LANGUAGE_COOKIE_NAME ?? import.meta.env.VITE_LANGUAGE_COOKIE_NAME,
  ENV_FONT_SIZE_COOKIE_NAME:
    window.ENV?.ENV_FONT_SIZE_COOKIE_NAME ?? import.meta.env.VITE_FONT_SIZE_COOKIE_NAME,

  ENV_FRONTEND_API_URL:
    window.ENV?.ENV_FRONTEND_API_URL ?? import.meta.env.VITE_FRONTEND_API_URL,

  ENV_RECAPTCHA_SITE_KEY:
    window.ENV?.ENV_RECAPTCHA_SITE_KEY ?? import.meta.env.VITE_RECAPTCHA_SITE_KEY,

  ENV_KEYCLOAK_REALM:
    window.ENV?.ENV_KEYCLOAK_REALM ?? import.meta.env.VITE_KEYCLOAK_REALM,
  ENV_KEYCLOAK_CLIENT_ID:
    window.ENV?.ENV_KEYCLOAK_CLIENT_ID ?? import.meta.env.VITE_KEYCLOAK_CLIENT_ID,
  ENV_KEYCLOAK_SERVER_URL:
    window.ENV?.ENV_KEYCLOAK_SERVER_URL ?? import.meta.env.VITE_KEYCLOAK_SERVER_URL,

  ENV_SERVICE_ROUTES:
    window.ENV_MFE?.ENV_SERVICE_ROUTES ?? import.meta.env.VITE_SERVICE_ROUTES,
  ENV_OWNED_PROPERTIES_ROUTES:
    window.ENV_MFE?.ENV_OWNED_PROPERTIES_ROUTES ??
    import.meta.env.VITE_OWNED_PROPERTIES_ROUTES,
}

export default env
